---
title: "Pubmed & Literature Retrieval"
subtitle: "ピロリ菌セミナー"
author: "王　超辰 | Chaochen Wang"
date: "2019-02-18"
output:
  xaringan::moon_reader:
    css: xaringan-themer.css
    lib_dir: libs
    nature:
      countdown: 60000
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r xaringan-themer, include = FALSE}
library(xaringanthemer)
mono_light(
  base_color = "#1c5253",
  header_font_google = google_font("Josefin Sans"),
  # text_font_google   = google_font("M PLUS Rounded 1c", "300", "300i"),
  text_font_google = google_font("Noto Sans JP", "300", "300i"), 
  code_font_google   = google_font("Droid Mono"),
  text_bold_color = "#B03A2E",
  title_slide_background_image = "pic/pylori.jpg"
)
# write_xaringan_theme(text_bold_color = "#FF4333")
```



class: middle
# 目標 <br> objectives

- Pubmedを知って，使ってもらう <br> Understand what is Pubmed and how to use it. 

- Meta-analysisとシステマティックレビューの基本を理解する <br> Introduction to meta-analysis


---
class: middle

## 効率的に文献を探すために <br> how to find literature efficiently?

- ツール <br> Tool

- 戦略 <br> Strategy

- 統合，秩序 <br> Organization

---
class: middle, center, inverse

## 文献とはなーに？ <br> What is literature?


---
class: middle

#### ある研究結果のまとめ？専門家から系統的な意見を発表する？<br> Papers with results and records of research, study, experience, experiment, or observation.

#### 今までわかったこと，別の研究者の同じ問題について考え方などを載せてある．<br> What have been done/known so far, and what others think about this issue. 

#### 教科書や科学雑誌に採用される文章？<br> Papers published in textbooks or scientific journals (Science, Nature, etc.)

#### 教科書は比較的にアップデートされるのが遅い傾向がある．<br> Textbooks are usually updated rarely and out-of-date.

---
class: middle, center, inverse

## なぜ検索しなければならない？<br> Why do we need literature retrieval?

---
class: middle


